id: UC-011-calcular-total
name: Calcular total do contrato
status: active

trigger:
  screen: TELA_CONTRATO
  component: INP_VALOR_MENSAL
  event: onBlur

main_flow:
  - step: Ler valorMensal e prazoMeses
  - step: Calcular total = valorMensal * prazoMeses
    refs:
      - RN-045
  - step: Atualizar LBL_TOTAL
